// resources/js/components/navigation/navbar.vue
<script setup lang="ts">
import { Props } from '@/types/components/navbar';
import { onMounted, onUnmounted, ref } from 'vue';

const props = defineProps<Props>();

const isVisible = ref(false);
const lastScrollY = ref(0);

const handleScroll = () => {
    const currentScrollY = window.scrollY;

    if (props.alwaysShowNavbar) {
        isVisible.value = true;
    } else {
        isVisible.value = currentScrollY > 100;
    }

    lastScrollY.value = currentScrollY;
};

onMounted(() => {
    if (props.alwaysShowNavbar) {
        isVisible.value = true;
    } else {
        handleScroll();
    }

    window.addEventListener('scroll', handleScroll);
});

onUnmounted(() => {
    window.removeEventListener('scroll', handleScroll);
});
</script>

<template>
    <nav
        class="fixed top-0 right-0 left-0 z-50 transition-all duration-300 ease-in-out"
        :class="isVisible ? 'translate-y-0 bg-[#111]/90 opacity-100 shadow-md backdrop-blur-sm' : '-translate-y-full opacity-0'"
    >
        <div class="container mx-auto flex items-center justify-between px-4 py-4">
            <div class="text-xl font-bold">
                <a href="/" class="transition-colors duration-300 hover:text-purple-400">Riley Edward</a>
            </div>

            <div class="flex space-x-12">
                <a href="#" class="transition-colors duration-300 hover:text-cyan-400">About</a>
                <a href="#" class="transition-colors duration-300 hover:text-cyan-400">Portfolio</a>
                <a href="#" class="transition-colors duration-300 hover:text-cyan-400">Blog</a>
            </div>
        </div>
    </nav>
</template>

// src/lib/components/navigation/Navbar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { showContactModal } from '$lib/store';

	$: pathname = $page.url.pathname;
</script>

<nav>
	<div class="max-w-5xl mx-auto flex justify-between items-center px-8 py-6">
		<div class="flex items-center gap-24">
			<h1 class="text-2xl font-bold">
				<a href="/" class="hover:text-violet-500">
					Riley Edward
					<span class="text-violet-500">.</span>
				</a>
			</h1>

			<ul class="flex items-center gap-12">
				<li
					class={`font-light text-sm hover:font-semibold ${pathname.includes('/projects') ? 'text-violet-500' : 'hover:text-violet-500'}`}
				>
					<a href="/projects"> Projects </a>
				</li>
				<li
					class={`font-light text-sm hover:font-semibold ${pathname.includes('/blog') ? 'text-violet-500' : 'hover:text-violet-500'}`}
				>
					<a href="/blog"> Blog </a>
				</li>
			</ul>
		</div>

		<div class="flex items-center gap-8">
			<button
				class="w-full py-1 px-6 bg-violet-500 text-white hover:font-semibold rounded-md shadow-md hover:bg-violet-400 focus:outline-none focus:ring-2 focus:ring-violet-500 focus:ring-opacity-50 transition duration-150 ease-in-out"
				on:click={() => ($showContactModal = true)}
			>
				contact
			</button>
		</div>
	</div>
</nav>
